"""Add 'end_date' to 'activity'

Revision ID: fb9bea0c9c2b
Revises: f6100d1dcb4b
Create Date: 2024-11-11 14:09:44.906798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb9bea0c9c2b'
down_revision: Union[str, None] = 'f6100d1dcb4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('activity', sa.Column('status', sa.String(length=20), nullable=True))
    op.alter_column('activity', 'duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('activity', 'distance_meters',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('activity', 'last_update_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('last_update_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('activity', 'distance_meters',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('activity', 'duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('activity', 'status')
    op.drop_column('activity', 'end_date')
    # ### end Alembic commands ###
