"""Initial migration

Revision ID: e8650a4810b9
Revises: 633d4102849a
Create Date: 2024-10-10 14:26:14.254557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8650a4810b9'
down_revision = '633d4102849a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('activity', sa.Column('last_update_date', sa.DateTime(), nullable=True))
    op.drop_column('activity', 'datetime')
    op.add_column('goal', sa.Column('last_update_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'last_update_date')
    op.add_column('activity', sa.Column('datetime', sa.DATETIME(), nullable=True))
    op.drop_column('activity', 'last_update_date')
    op.drop_column('activity', 'start_date')
    # ### end Alembic commands ###
